export enum CategoriasEnum {
  TECNOLOGIA = 'Tecnología',
  CELULARES_Y_ACCESORIOS = 'Celulares y Accesorios',
  COMPUTADORES = 'Computadores',
  COMIDAS = 'Comidas',
  ENTRETENIMIENTO = 'Entretenimiento',
  ELECTRONICOS = 'Electrónicos',
  HOGAR = 'Hogar',
  IMPRESORAS = 'Impresoras',
  LINEA_BLANCA = 'Línea blanca',
  SERVICIOS = 'Servicios',
  VESTUARIO_Y_COMPLEMENTOS = 'Vestuario y complementos',
  VIDEOJUEGOS = 'Videojuegos',
  OFICINAS = 'Oficinas',
}
